// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdxQlb6Uw-19QH_Qz96eqtp_d2UnDfzk',
    appId: '1:703592972172:web:24d0f1f37df980a5f3e0a9',
    messagingSenderId: '703592972172',
    projectId: 'to-do-apps-5cdca',
    authDomain: 'to-do-apps-5cdca.firebaseapp.com',
    storageBucket: 'to-do-apps-5cdca.firebasestorage.app',
    measurementId: 'G-K6CZBR3WPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDljrqRkfpwUbCsmW6BXaVQef5jSgwkoEU',
    appId: '1:703592972172:android:c1b892866309bf75f3e0a9',
    messagingSenderId: '703592972172',
    projectId: 'to-do-apps-5cdca',
    storageBucket: 'to-do-apps-5cdca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTci3dwQl0wm1DbPt4M7CElZuRr_B92Vg',
    appId: '1:703592972172:ios:20a653092b0be283f3e0a9',
    messagingSenderId: '703592972172',
    projectId: 'to-do-apps-5cdca',
    storageBucket: 'to-do-apps-5cdca.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTci3dwQl0wm1DbPt4M7CElZuRr_B92Vg',
    appId: '1:703592972172:ios:20a653092b0be283f3e0a9',
    messagingSenderId: '703592972172',
    projectId: 'to-do-apps-5cdca',
    storageBucket: 'to-do-apps-5cdca.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQdxQlb6Uw-19QH_Qz96eqtp_d2UnDfzk',
    appId: '1:703592972172:web:1025a2f0727648bbf3e0a9',
    messagingSenderId: '703592972172',
    projectId: 'to-do-apps-5cdca',
    authDomain: 'to-do-apps-5cdca.firebaseapp.com',
    storageBucket: 'to-do-apps-5cdca.firebasestorage.app',
    measurementId: 'G-S0HRTG0G9F',
  );

}